husky_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

husky_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50
  base_frame_id: base_link
  enable_odom_tf: false
  cmd_vel_timeout: 0.25
  velocity_rolling_window_size: 2

  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']

  wheel_separation_multiplier: 1.875
  wheel_radius_multiplier: 1.0

  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 3.0

  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 6.0

  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.001]
