forest_robot:
  # Joint state controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Wheel velocity controllers
  front_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left_wheel_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
  
  front_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
  
  rear_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_left_wheel_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
  
  rear_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_right_wheel_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}