twist_mux:
  topics:
    - name: joy
      topic: joy_teleop/cmd_vel
      timeout: 0.5
      priority: 10
    - name: keyboard
      topic: teleop_twist_keyboard/cmd_vel
      timeout: 0.5
      priority: 9
    - name: interactive_marker
      topic: twist_marker_server/cmd_vel
      timeout: 0.5
      priority: 8
  
  locks:
    - name: e_stop
      topic: e_stop
      timeout: 0.0
      priority: 255
    - name: slow_zone
      topic: slow_zone
      timeout: 0.0
      priority: 200